// const countries = [
//   "Afghanistan",
//   "Albania",
//   "Algeria",
//   "American Samoa",
//   "Andorra",
//   "Angola",
//   "Anguilla",
//   "Antarctica",
//   "Antigua and Barbuda",
//   "Argentina",
//   "Armenia",
//   "Aruba",
//   "Australia",
//   "Austria",
//   "Azerbaijan",
//   "Bahamas",
//   "Bahrain",
//   "Bangladesh",
//   "Barbados",
//   "Belarus",
//   "Belgium",
//   "Belize",
//   "Benin",
//   "Bermuda",
//   "Bhutan",
//   "Bolivia",
//   "Bosnia and Herzegowina",
//   "Botswana",
//   "Bouvet Island",
//   "Brazil",
//   "British Indian Ocean Territory",
//   "Brunei Darussalam",
//   "Bulgaria",
//   "Burkina Faso",
//   "Burundi",
//   "Cambodia",
//   "Cameroon",
//   "Canada",
//   "Cape Verde",
//   "Cayman Islands",
//   "Central African Republic",
//   "Chad",
//   "Chile",
//   "China",
//   "Christmas Island",
//   "Cocos (Keeling) Islands",
//   "Colombia",
//   "Comoros",
//   "Congo",
//   "Congo, the Democratic Republic of the",
//   "Cook Islands",
//   "Costa Rica",
//   "Cote d'Ivoire",
//   "Croatia (Hrvatska)",
//   "Cuba",
//   "Cyprus",
//   "Czech Republic",
//   "Denmark",
//   "Djibouti",
//   "Dominica",
//   "Dominican Republic",
//   "East Timor",
//   "Ecuador",
//   "Egypt",
//   "El Salvador",
//   "Equatorial Guinea",
//   "Eritrea",
//   "Estonia",
//   "Ethiopia",
//   "Falkland Islands (Malvinas)",
//   "Faroe Islands",
//   "Fiji",
//   "Finland",
//   "France",
//   "France Metropolitan",
//   "French Guiana",
//   "French Polynesia",
//   "French Southern Territories",
//   "Gabon",
//   "Gambia",
//   "Georgia",
//   "Germany",
//   "Ghana",
//   "Gibraltar",
//   "Greece",
//   "Greenland",
//   "Grenada",
//   "Guadeloupe",
//   "Guam",
//   "Guatemala",
//   "Guinea",
//   "Guinea-Bissau",
//   "Guyana",
//   "Haiti",
//   "Heard and Mc Donald Islands",
//   "Holy See (Vatican City State)",
//   "Honduras",
//   "Hong Kong",
//   "Hungary",
//   "Iceland",
//   "India",
//   "Indonesia",
//   "Iran (Islamic Republic of)",
//   "Iraq",
//   "Ireland",
//   "Israel",
//   "Italy",
//   "Jamaica",
//   "Japan",
//   "Jordan",
//   "Kazakhstan",
//   "Kenya",
//   "Kiribati",
//   "Korea, Democratic People's Republic of",
//   "Korea, Republic of",
//   "Kuwait",
//   "Kyrgyzstan",
//   "Lao, People's Democratic Republic",
//   "Latvia",
//   "Lebanon",
//   "Lesotho",
//   "Liberia",
//   "Libyan Arab Jamahiriya",
//   "Liechtenstein",
//   "Lithuania",
//   "Luxembourg",
//   "Macau",
//   "Macedonia, The Former Yugoslav Republic of",
//   "Madagascar",
//   "Malawi",
//   "Malaysia",
//   "Maldives",
//   "Mali",
//   "Malta",
//   "Marshall Islands",
//   "Martinique",
//   "Mauritania",
//   "Mauritius",
//   "Mayotte",
//   "Mexico",
//   "Micronesia, Federated States of",
//   "Moldova, Republic of",
//   "Monaco",
//   "Mongolia",
//   "Montserrat",
//   "Morocco",
//   "Mozambique",
//   "Myanmar",
//   "Namibia",
//   "Nauru",
//   "Nepal",
//   "Netherlands",
//   "Netherlands Antilles",
//   "New Caledonia",
//   "New Zealand",
//   "Nicaragua",
//   "Niger",
//   "Nigeria",
//   "Niue",
//   "Norfolk Island",
//   "Northern Mariana Islands",
//   "Norway",
//   "Oman",
//   "Pakistan",
//   "Palau",
//   "Panama",
//   "Papua New Guinea",
//   "Paraguay",
//   "Peru",
//   "Philippines",
//   "Pitcairn",
//   "Poland",
//   "Portugal",
//   "Puerto Rico",
//   "Qatar",
//   "Reunion",
//   "Romania",
//   "Russian Federation",
//   "Rwanda",
//   "Saint Kitts and Nevis",
//   "Saint Lucia",
//   "Saint Vincent and the Grenadines",
//   "Samoa",
//   "San Marino",
//   "Sao Tome and Principe",
//   "Saudi Arabia",
//   "Senegal",
//   "Seychelles",
//   "Sierra Leone",
//   "Singapore",
//   "Slovakia (Slovak Republic)",
//   "Slovenia",
//   "Solomon Islands",
//   "Somalia",
//   "South Africa",
//   "South Georgia and the South Sandwich Islands",
//   "Spain",
//   "Sri Lanka",
//   "St. Helena",
//   "St. Pierre and Miquelon",
//   "Sudan",
//   "Suriname",
//   "Svalbard and Jan Mayen Islands",
//   "Swaziland",
//   "Sweden",
//   "Switzerland",
//   "Syrian Arab Republic",
//   "Taiwan, Province of China",
//   "Tajikistan",
//   "Tanzania, United Republic of",
//   "Thailand",
//   "Togo",
//   "Tokelau",
//   "Tonga",
//   "Trinidad and Tobago",
//   "Tunisia",
//   "Turkey",
//   "Turkmenistan",
//   "Turks and Caicos Islands",
//   "Tuvalu",
//   "Uganda",
//   "Ukraine",
//   "United Arab Emirates",
//   "United Kingdom",
//   "United States",
//   "United States Minor Outlying Islands",
//   "Uruguay",
//   "Uzbekistan",
//   "Vanuatu",
//   "Venezuela",
//   "Vietnam",
//   "Virgin Islands (British)",
//   "Virgin Islands (U.S.)",
//   "Wallis and Futuna Islands",
//   "Western Sahara",
//   "Yemen",
//   "Yugoslavia",
//   "Zambia",
//   "Zimbabwe",
// ];

const countries = [
  {
    Country: "Saint Lucia",
    Slug: "saint-lucia",
    ISO2: "LC",
  },
  {
    Country: "United States of America",
    Slug: "united-states",
    ISO2: "US",
  },
  {
    Country: "Albania",
    Slug: "albania",
    ISO2: "AL",
  },
  {
    Country: "Cameroon",
    Slug: "cameroon",
    ISO2: "CM",
  },
  {
    Country: "Estonia",
    Slug: "estonia",
    ISO2: "EE",
  },
  {
    Country: "French Southern Territories",
    Slug: "french-southern-territories",
    ISO2: "TF",
  },
  {
    Country: "Spain",
    Slug: "spain",
    ISO2: "ES",
  },
  {
    Country: "Virgin Islands, US",
    Slug: "virgin-islands",
    ISO2: "VI",
  },
  {
    Country: "Hong Kong, SAR China",
    Slug: "hong-kong-sar-china",
    ISO2: "HK",
  },
  {
    Country: "Mali",
    Slug: "mali",
    ISO2: "ML",
  },
  {
    Country: "Netherlands",
    Slug: "netherlands",
    ISO2: "NL",
  },
  {
    Country: "Korea (South)",
    Slug: "korea-south",
    ISO2: "KR",
  },
  {
    Country: "Norway",
    Slug: "norway",
    ISO2: "NO",
  },
  {
    Country: "Fiji",
    Slug: "fiji",
    ISO2: "FJ",
  },
  {
    Country: "Greece",
    Slug: "greece",
    ISO2: "GR",
  },
  {
    Country: "Guyana",
    Slug: "guyana",
    ISO2: "GY",
  },
  {
    Country: "Tanzania, United Republic of",
    Slug: "tanzania",
    ISO2: "TZ",
  },
  {
    Country: "American Samoa",
    Slug: "american-samoa",
    ISO2: "AS",
  },
  {
    Country: "Antigua and Barbuda",
    Slug: "antigua-and-barbuda",
    ISO2: "AG",
  },
  {
    Country: "Canada",
    Slug: "canada",
    ISO2: "CA",
  },
  {
    Country: "Heard and Mcdonald Islands",
    Slug: "heard-and-mcdonald-islands",
    ISO2: "HM",
  },
  {
    Country: "Cape Verde",
    Slug: "cape-verde",
    ISO2: "CV",
  },
  {
    Country: "Mauritius",
    Slug: "mauritius",
    ISO2: "MU",
  },
  {
    Country: "Micronesia, Federated States of",
    Slug: "micronesia",
    ISO2: "FM",
  },
  {
    Country: "Myanmar",
    Slug: "myanmar",
    ISO2: "MM",
  },
  {
    Country: "Guam",
    Slug: "guam",
    ISO2: "GU",
  },
  {
    Country: "Palau",
    Slug: "palau",
    ISO2: "PW",
  },
  {
    Country: "Solomon Islands",
    Slug: "solomon-islands",
    ISO2: "SB",
  },
  {
    Country: "Wallis and Futuna Islands",
    Slug: "wallis-and-futuna-islands",
    ISO2: "WF",
  },
  {
    Country: "Guadeloupe",
    Slug: "guadeloupe",
    ISO2: "GP",
  },
  {
    Country: "Hungary",
    Slug: "hungary",
    ISO2: "HU",
  },
  {
    Country: "Saudi Arabia",
    Slug: "saudi-arabia",
    ISO2: "SA",
  },
  {
    Country: "Denmark",
    Slug: "denmark",
    ISO2: "DK",
  },
  {
    Country: "Brunei Darussalam",
    Slug: "brunei",
    ISO2: "BN",
  },
  {
    Country: "Cayman Islands",
    Slug: "cayman-islands",
    ISO2: "KY",
  },
  {
    Country: "Comoros",
    Slug: "comoros",
    ISO2: "KM",
  },
  {
    Country: "United Kingdom",
    Slug: "united-kingdom",
    ISO2: "GB",
  },
  {
    Country: "Chad",
    Slug: "chad",
    ISO2: "TD",
  },
  {
    Country: "Uganda",
    Slug: "uganda",
    ISO2: "UG",
  },
  {
    Country: "Namibia",
    Slug: "namibia",
    ISO2: "NA",
  },
  {
    Country: "Samoa",
    Slug: "samoa",
    ISO2: "WS",
  },
  {
    Country: "Tunisia",
    Slug: "tunisia",
    ISO2: "TN",
  },
  {
    Country: "Argentina",
    Slug: "argentina",
    ISO2: "AR",
  },
  {
    Country: "Belgium",
    Slug: "belgium",
    ISO2: "BE",
  },
  {
    Country: "Dominica",
    Slug: "dominica",
    ISO2: "DM",
  },
  {
    Country: "Mexico",
    Slug: "mexico",
    ISO2: "MX",
  },
  {
    Country: "Bermuda",
    Slug: "bermuda",
    ISO2: "BM",
  },
  {
    Country: "Indonesia",
    Slug: "indonesia",
    ISO2: "ID",
  },
  {
    Country: "Kenya",
    Slug: "kenya",
    ISO2: "KE",
  },
  {
    Country: "Kyrgyzstan",
    Slug: "kyrgyzstan",
    ISO2: "KG",
  },
  {
    Country: "Guinea-Bissau",
    Slug: "guinea-bissau",
    ISO2: "GW",
  },
  {
    Country: "Malta",
    Slug: "malta",
    ISO2: "MT",
  },
  {
    Country: "Monaco",
    Slug: "monaco",
    ISO2: "MC",
  },
  {
    Country: "Armenia",
    Slug: "armenia",
    ISO2: "AM",
  },
  {
    Country: "Nauru",
    Slug: "nauru",
    ISO2: "NR",
  },
  {
    Country: "Switzerland",
    Slug: "switzerland",
    ISO2: "CH",
  },
  {
    Country: "Benin",
    Slug: "benin",
    ISO2: "BJ",
  },
  {
    Country: "Grenada",
    Slug: "grenada",
    ISO2: "GD",
  },
  {
    Country: "Netherlands Antilles",
    Slug: "netherlands-antilles",
    ISO2: "AN",
  },
  {
    Country: "Turkmenistan",
    Slug: "turkmenistan",
    ISO2: "TM",
  },
  {
    Country: "Papua New Guinea",
    Slug: "papua-new-guinea",
    ISO2: "PG",
  },
  {
    Country: "Saint Kitts and Nevis",
    Slug: "saint-kitts-and-nevis",
    ISO2: "KN",
  },
  {
    Country: "Nepal",
    Slug: "nepal",
    ISO2: "NP",
  },
  {
    Country: "Australia",
    Slug: "australia",
    ISO2: "AU",
  },
  {
    Country: "Brazil",
    Slug: "brazil",
    ISO2: "BR",
  },
  {
    Country: "India",
    Slug: "india",
    ISO2: "IN",
  },
  {
    Country: "El Salvador",
    Slug: "el-salvador",
    ISO2: "SV",
  },
  {
    Country: "Tokelau",
    Slug: "tokelau",
    ISO2: "TK",
  },
  {
    Country: "Tonga",
    Slug: "tonga",
    ISO2: "TO",
  },
  {
    Country: "Anguilla",
    Slug: "anguilla",
    ISO2: "AI",
  },
  {
    Country: "Venezuela (Bolivarian Republic)",
    Slug: "venezuela",
    ISO2: "VE",
  },
  {
    Country: "Nicaragua",
    Slug: "nicaragua",
    ISO2: "NI",
  },
  {
    Country: "Macedonia, Republic of",
    Slug: "macedonia",
    ISO2: "MK",
  },
  {
    Country: "Oman",
    Slug: "oman",
    ISO2: "OM",
  },
  {
    Country: "Rwanda",
    Slug: "rwanda",
    ISO2: "RW",
  },
  {
    Country: "Republic of Kosovo",
    Slug: "kosovo",
    ISO2: "XK",
  },
  {
    Country: "Algeria",
    Slug: "algeria",
    ISO2: "DZ",
  },
  {
    Country: "Bahrain",
    Slug: "bahrain",
    ISO2: "BH",
  },
  {
    Country: "Côte d'Ivoire",
    Slug: "cote-divoire",
    ISO2: "CI",
  },
  {
    Country: "Northern Mariana Islands",
    Slug: "northern-mariana-islands",
    ISO2: "MP",
  },
  {
    Country: "Bhutan",
    Slug: "bhutan",
    ISO2: "BT",
  },
  {
    Country: "Colombia",
    Slug: "colombia",
    ISO2: "CO",
  },
  {
    Country: "Guatemala",
    Slug: "guatemala",
    ISO2: "GT",
  },
  {
    Country: "Luxembourg",
    Slug: "luxembourg",
    ISO2: "LU",
  },
  {
    Country: "Iceland",
    Slug: "iceland",
    ISO2: "IS",
  },
  {
    Country: "Lao PDR",
    Slug: "lao-pdr",
    ISO2: "LA",
  },
  {
    Country: "Lithuania",
    Slug: "lithuania",
    ISO2: "LT",
  },
  {
    Country: "Bouvet Island",
    Slug: "bouvet-island",
    ISO2: "BV",
  },
  {
    Country: "Guernsey",
    Slug: "guernsey",
    ISO2: "GG",
  },
  {
    Country: "Germany",
    Slug: "germany",
    ISO2: "DE",
  },
  {
    Country: "Liechtenstein",
    Slug: "liechtenstein",
    ISO2: "LI",
  },
  {
    Country: "Palestinian Territory",
    Slug: "palestine",
    ISO2: "PS",
  },
  {
    Country: "Pitcairn",
    Slug: "pitcairn",
    ISO2: "PN",
  },
  {
    Country: "Zimbabwe",
    Slug: "zimbabwe",
    ISO2: "ZW",
  },
  {
    Country: "Croatia",
    Slug: "croatia",
    ISO2: "HR",
  },
  {
    Country: "Japan",
    Slug: "japan",
    ISO2: "JP",
  },
  {
    Country: "Montenegro",
    Slug: "montenegro",
    ISO2: "ME",
  },
  {
    Country: "Peru",
    Slug: "peru",
    ISO2: "PE",
  },
  {
    Country: "Cambodia",
    Slug: "cambodia",
    ISO2: "KH",
  },
  {
    Country: "Portugal",
    Slug: "portugal",
    ISO2: "PT",
  },
  {
    Country: "San Marino",
    Slug: "san-marino",
    ISO2: "SM",
  },
  {
    Country: "Jamaica",
    Slug: "jamaica",
    ISO2: "JM",
  },
  {
    Country: "Nigeria",
    Slug: "nigeria",
    ISO2: "NG",
  },
  {
    Country: "Poland",
    Slug: "poland",
    ISO2: "PL",
  },
  {
    Country: "South Africa",
    Slug: "south-africa",
    ISO2: "ZA",
  },
  {
    Country: "Jersey",
    Slug: "jersey",
    ISO2: "JE",
  },
  {
    Country: "Togo",
    Slug: "togo",
    ISO2: "TG",
  },
  {
    Country: "Gambia",
    Slug: "gambia",
    ISO2: "GM",
  },
  {
    Country: "Lebanon",
    Slug: "lebanon",
    ISO2: "LB",
  },
  {
    Country: "Saint Helena",
    Slug: "saint-helena",
    ISO2: "SH",
  },
  {
    Country: "Equatorial Guinea",
    Slug: "equatorial-guinea",
    ISO2: "GQ",
  },
  {
    Country: "Mayotte",
    Slug: "mayotte",
    ISO2: "YT",
  },
  {
    Country: "Saint Pierre and Miquelon",
    Slug: "saint-pierre-and-miquelon",
    ISO2: "PM",
  },
  {
    Country: "Andorra",
    Slug: "andorra",
    ISO2: "AD",
  },
  {
    Country: "Eritrea",
    Slug: "eritrea",
    ISO2: "ER",
  },
  {
    Country: "Gibraltar",
    Slug: "gibraltar",
    ISO2: "GI",
  },
  {
    Country: "Somalia",
    Slug: "somalia",
    ISO2: "SO",
  },
  {
    Country: "US Minor Outlying Islands",
    Slug: "us-minor-outlying-islands",
    ISO2: "UM",
  },
  {
    Country: "French Guiana",
    Slug: "french-guiana",
    ISO2: "GF",
  },
  {
    Country: "Italy",
    Slug: "italy",
    ISO2: "IT",
  },
  {
    Country: "Montserrat",
    Slug: "montserrat",
    ISO2: "MS",
  },
  {
    Country: "Morocco",
    Slug: "morocco",
    ISO2: "MA",
  },
  {
    Country: "Moldova",
    Slug: "moldova",
    ISO2: "MD",
  },
  {
    Country: "Senegal",
    Slug: "senegal",
    ISO2: "SN",
  },
  {
    Country: "Thailand",
    Slug: "thailand",
    ISO2: "TH",
  },
  {
    Country: "French Polynesia",
    Slug: "french-polynesia",
    ISO2: "PF",
  },
  {
    Country: "Ireland",
    Slug: "ireland",
    ISO2: "IE",
  },
  {
    Country: "Sri Lanka",
    Slug: "sri-lanka",
    ISO2: "LK",
  },
  {
    Country: "Trinidad and Tobago",
    Slug: "trinidad-and-tobago",
    ISO2: "TT",
  },
  {
    Country: "Niger",
    Slug: "niger",
    ISO2: "NE",
  },
  {
    Country: "Egypt",
    Slug: "egypt",
    ISO2: "EG",
  },
  {
    Country: "Guinea",
    Slug: "guinea",
    ISO2: "GN",
  },
  {
    Country: "Mozambique",
    Slug: "mozambique",
    ISO2: "MZ",
  },
  {
    Country: "France",
    Slug: "france",
    ISO2: "FR",
  },
  {
    Country: "Haiti",
    Slug: "haiti",
    ISO2: "HT",
  },
  {
    Country: "Israel",
    Slug: "israel",
    ISO2: "IL",
  },
  {
    Country: "Russian Federation",
    Slug: "russia",
    ISO2: "RU",
  },
  {
    Country: "Bahamas",
    Slug: "bahamas",
    ISO2: "BS",
  },
  {
    Country: "Congo (Brazzaville)",
    Slug: "congo-brazzaville",
    ISO2: "CG",
  },
  {
    Country: "Saint-Barthélemy",
    Slug: "saint-barthélemy",
    ISO2: "BL",
  },
  {
    Country: "Slovenia",
    Slug: "slovenia",
    ISO2: "SI",
  },
  {
    Country: "Uruguay",
    Slug: "uruguay",
    ISO2: "UY",
  },
  {
    Country: "Paraguay",
    Slug: "paraguay",
    ISO2: "PY",
  },
  {
    Country: "Swaziland",
    Slug: "swaziland",
    ISO2: "SZ",
  },
  {
    Country: "Maldives",
    Slug: "maldives",
    ISO2: "MV",
  },
  {
    Country: "Slovakia",
    Slug: "slovakia",
    ISO2: "SK",
  },
  {
    Country: "Angola",
    Slug: "angola",
    ISO2: "AO",
  },
  {
    Country: "Bangladesh",
    Slug: "bangladesh",
    ISO2: "BD",
  },
  {
    Country: "Iraq",
    Slug: "iraq",
    ISO2: "IQ",
  },
  {
    Country: "Isle of Man",
    Slug: "isle-of-man",
    ISO2: "IM",
  },
  {
    Country: "Lesotho",
    Slug: "lesotho",
    ISO2: "LS",
  },
  {
    Country: "Macao, SAR China",
    Slug: "macao-sar-china",
    ISO2: "MO",
  },
  {
    Country: "South Georgia and the South Sandwich Islands",
    Slug: "south-georgia-and-the-south-sandwich-islands",
    ISO2: "GS",
  },
  {
    Country: "Costa Rica",
    Slug: "costa-rica",
    ISO2: "CR",
  },
  {
    Country: "Czech Republic",
    Slug: "czech-republic",
    ISO2: "CZ",
  },
  {
    Country: "Ghana",
    Slug: "ghana",
    ISO2: "GH",
  },
  {
    Country: "Honduras",
    Slug: "honduras",
    ISO2: "HN",
  },
  {
    Country: "Belarus",
    Slug: "belarus",
    ISO2: "BY",
  },
  {
    Country: "Belize",
    Slug: "belize",
    ISO2: "BZ",
  },
  {
    Country: "Iran, Islamic Republic of",
    Slug: "iran",
    ISO2: "IR",
  },
  {
    Country: "Mongolia",
    Slug: "mongolia",
    ISO2: "MN",
  },
  {
    Country: "Turkey",
    Slug: "turkey",
    ISO2: "TR",
  },
  {
    Country: "Uzbekistan",
    Slug: "uzbekistan",
    ISO2: "UZ",
  },
  {
    Country: "Burundi",
    Slug: "burundi",
    ISO2: "BI",
  },
  {
    Country: "Cuba",
    Slug: "cuba",
    ISO2: "CU",
  },
  {
    Country: "Timor-Leste",
    Slug: "timor-leste",
    ISO2: "TL",
  },
  {
    Country: "Austria",
    Slug: "austria",
    ISO2: "AT",
  },
  {
    Country: "Cook Islands",
    Slug: "cook-islands",
    ISO2: "CK",
  },
  {
    Country: "Pakistan",
    Slug: "pakistan",
    ISO2: "PK",
  },
  {
    Country: "Falkland Islands (Malvinas)",
    Slug: "falkland-islands-malvinas",
    ISO2: "FK",
  },
  {
    Country: "Martinique",
    Slug: "martinique",
    ISO2: "MQ",
  },
  {
    Country: "South Sudan",
    Slug: "south-sudan",
    ISO2: "SS",
  },
  {
    Country: "Ukraine",
    Slug: "ukraine",
    ISO2: "UA",
  },
  {
    Country: "China",
    Slug: "china",
    ISO2: "CN",
  },
  {
    Country: "Kuwait",
    Slug: "kuwait",
    ISO2: "KW",
  },
  {
    Country: "Yemen",
    Slug: "yemen",
    ISO2: "YE",
  },
  {
    Country: "Azerbaijan",
    Slug: "azerbaijan",
    ISO2: "AZ",
  },
  {
    Country: "Chile",
    Slug: "chile",
    ISO2: "CL",
  },
  {
    Country: "Malaysia",
    Slug: "malaysia",
    ISO2: "MY",
  },
  {
    Country: "Saint Vincent and Grenadines",
    Slug: "saint-vincent-and-the-grenadines",
    ISO2: "VC",
  },
  {
    Country: "Congo (Kinshasa)",
    Slug: "congo-kinshasa",
    ISO2: "CD",
  },
  {
    Country: "Djibouti",
    Slug: "djibouti",
    ISO2: "DJ",
  },
  {
    Country: "Greenland",
    Slug: "greenland",
    ISO2: "GL",
  },
  {
    Country: "Marshall Islands",
    Slug: "marshall-islands",
    ISO2: "MH",
  },
  {
    Country: "Afghanistan",
    Slug: "afghanistan",
    ISO2: "AF",
  },
  {
    Country: "Bolivia",
    Slug: "bolivia",
    ISO2: "BO",
  },
  {
    Country: "Burkina Faso",
    Slug: "burkina-faso",
    ISO2: "BF",
  },
  {
    Country: "Saint-Martin (French part)",
    Slug: "saint-martin-french-part",
    ISO2: "MF",
  },
  {
    Country: "Western Sahara",
    Slug: "western-sahara",
    ISO2: "EH",
  },
  {
    Country: "Sao Tome and Principe",
    Slug: "sao-tome-and-principe",
    ISO2: "ST",
  },
  {
    Country: "Finland",
    Slug: "finland",
    ISO2: "FI",
  },
  {
    Country: "Mauritania",
    Slug: "mauritania",
    ISO2: "MR",
  },
  {
    Country: "Philippines",
    Slug: "philippines",
    ISO2: "PH",
  },
  {
    Country: "Suriname",
    Slug: "suriname",
    ISO2: "SR",
  },
  {
    Country: "Svalbard and Jan Mayen Islands",
    Slug: "svalbard-and-jan-mayen-islands",
    ISO2: "SJ",
  },
  {
    Country: "Turks and Caicos Islands",
    Slug: "turks-and-caicos-islands",
    ISO2: "TC",
  },
  {
    Country: "United Arab Emirates",
    Slug: "united-arab-emirates",
    ISO2: "AE",
  },
  {
    Country: "Aruba",
    Slug: "aruba",
    ISO2: "AW",
  },
  {
    Country: "British Virgin Islands",
    Slug: "british-virgin-islands",
    ISO2: "VG",
  },
  {
    Country: "Cyprus",
    Slug: "cyprus",
    ISO2: "CY",
  },
  {
    Country: "Réunion",
    Slug: "réunion",
    ISO2: "RE",
  },
  {
    Country: "Central African Republic",
    Slug: "central-african-republic",
    ISO2: "CF",
  },
  {
    Country: "Puerto Rico",
    Slug: "puerto-rico",
    ISO2: "PR",
  },
  {
    Country: "Sierra Leone",
    Slug: "sierra-leone",
    ISO2: "SL",
  },
  {
    Country: "Syrian Arab Republic (Syria)",
    Slug: "syria",
    ISO2: "SY",
  },
  {
    Country: "Taiwan, Republic of China",
    Slug: "taiwan",
    ISO2: "TW",
  },
  {
    Country: "Antarctica",
    Slug: "antarctica",
    ISO2: "AQ",
  },
  {
    Country: "Norfolk Island",
    Slug: "norfolk-island",
    ISO2: "NF",
  },
  {
    Country: "Qatar",
    Slug: "qatar",
    ISO2: "QA",
  },
  {
    Country: "Seychelles",
    Slug: "seychelles",
    ISO2: "SC",
  },
  {
    Country: "Tajikistan",
    Slug: "tajikistan",
    ISO2: "TJ",
  },
  {
    Country: "ALA Aland Islands",
    Slug: "ala-aland-islands",
    ISO2: "AX",
  },
  {
    Country: "Cocos (Keeling) Islands",
    Slug: "cocos-keeling-islands",
    ISO2: "CC",
  },
  {
    Country: "Malawi",
    Slug: "malawi",
    ISO2: "MW",
  },
  {
    Country: "Sudan",
    Slug: "sudan",
    ISO2: "SD",
  },
  {
    Country: "Georgia",
    Slug: "georgia",
    ISO2: "GE",
  },
  {
    Country: "Korea (North)",
    Slug: "korea-north",
    ISO2: "KP",
  },
  {
    Country: "Madagascar",
    Slug: "madagascar",
    ISO2: "MG",
  },
  {
    Country: "Botswana",
    Slug: "botswana",
    ISO2: "BW",
  },
  {
    Country: "Dominican Republic",
    Slug: "dominican-republic",
    ISO2: "DO",
  },
  {
    Country: "Ethiopia",
    Slug: "ethiopia",
    ISO2: "ET",
  },
  {
    Country: "Holy See (Vatican City State)",
    Slug: "holy-see-vatican-city-state",
    ISO2: "VA",
  },
  {
    Country: "Barbados",
    Slug: "barbados",
    ISO2: "BB",
  },
  {
    Country: "Niue",
    Slug: "niue",
    ISO2: "NU",
  },
  {
    Country: "Romania",
    Slug: "romania",
    ISO2: "RO",
  },
  {
    Country: "Singapore",
    Slug: "singapore",
    ISO2: "SG",
  },
  {
    Country: "British Indian Ocean Territory",
    Slug: "british-indian-ocean-territory",
    ISO2: "IO",
  },
  {
    Country: "Faroe Islands",
    Slug: "faroe-islands",
    ISO2: "FO",
  },
  {
    Country: "Jordan",
    Slug: "jordan",
    ISO2: "JO",
  },
  {
    Country: "Kiribati",
    Slug: "kiribati",
    ISO2: "KI",
  },
  {
    Country: "Tuvalu",
    Slug: "tuvalu",
    ISO2: "TV",
  },
  {
    Country: "Viet Nam",
    Slug: "vietnam",
    ISO2: "VN",
  },
  {
    Country: "Kazakhstan",
    Slug: "kazakhstan",
    ISO2: "KZ",
  },
  {
    Country: "Latvia",
    Slug: "latvia",
    ISO2: "LV",
  },
  {
    Country: "New Zealand",
    Slug: "new-zealand",
    ISO2: "NZ",
  },
  {
    Country: "Sweden",
    Slug: "sweden",
    ISO2: "SE",
  },
  {
    Country: "Libya",
    Slug: "libya",
    ISO2: "LY",
  },
  {
    Country: "Zambia",
    Slug: "zambia",
    ISO2: "ZM",
  },
  {
    Country: "Bulgaria",
    Slug: "bulgaria",
    ISO2: "BG",
  },
  {
    Country: "Christmas Island",
    Slug: "christmas-island",
    ISO2: "CX",
  },
  {
    Country: "Ecuador",
    Slug: "ecuador",
    ISO2: "EC",
  },
  {
    Country: "Gabon",
    Slug: "gabon",
    ISO2: "GA",
  },
  {
    Country: "Panama",
    Slug: "panama",
    ISO2: "PA",
  },
  {
    Country: "Vanuatu",
    Slug: "vanuatu",
    ISO2: "VU",
  },
  {
    Country: "Bosnia and Herzegovina",
    Slug: "bosnia-and-herzegovina",
    ISO2: "BA",
  },
  {
    Country: "Liberia",
    Slug: "liberia",
    ISO2: "LR",
  },
  {
    Country: "New Caledonia",
    Slug: "new-caledonia",
    ISO2: "NC",
  },
  {
    Country: "Serbia",
    Slug: "serbia",
    ISO2: "RS",
  },
];

export default countries;
